tag @s remove aqua
tag @s remove black
tag @s remove blue
tag @s remove dark_aqua
tag @s remove dark_blue
tag @s remove dark_gray
tag @s remove dark_green
tag @s remove dark_purple
tag @s remove dark_red
tag @s remove gold
tag @s remove gray
tag @s remove green
tag @s remove light_purple
tag @s remove red
tag @s remove white
tag @s remove yellow